In [1]:
import torch

In [20]:
tt = torch.randn((2, 4, 8))
tt

tensor([[[-1.5142e-03, -1.4385e+00, -1.7212e-01, -5.8312e-01, -1.5803e+00,
          -2.1158e-01, -5.5694e-01,  2.8833e+00],
         [-2.3104e-01,  1.2913e+00,  4.4618e-01, -9.8944e-01, -4.8918e-01,
           9.7251e-01, -5.0376e-01,  3.2602e-01],
         [ 6.0209e-01, -1.6645e+00, -1.2018e+00,  5.0758e-01,  9.3773e-01,
           7.4054e-01,  1.3478e+00,  1.1064e+00],
         [-1.1671e+00, -1.2684e-01,  6.5639e-01,  1.6849e-01, -6.3959e-01,
          -2.0126e+00, -2.0802e-02,  1.1039e+00]],

        [[ 6.0124e-01, -1.0077e-01,  6.2424e-01, -1.3016e+00, -8.0290e-01,
           4.1694e-01,  1.1782e+00, -1.0553e+00],
         [-4.0076e-01,  4.8647e-01,  2.9187e-01, -3.8987e-01,  5.5880e-01,
           1.2655e-01, -8.1196e-01, -4.7109e-01],
         [ 6.9904e-01,  4.0829e-01,  5.3041e-01, -1.1796e+00, -3.0192e-01,
          -1.8486e+00, -5.2596e-01, -2.4192e-01],
         [ 7.5499e-01, -6.9229e-01, -3.1246e-01,  3.1820e-02,  3.5888e-02,
           9.6356e-01,  3.5283e-01,  1.4681e-01]

In [21]:
a, b = tt.split(4, dim=2)

In [22]:
a

tensor([[[-1.5142e-03, -1.4385e+00, -1.7212e-01, -5.8312e-01],
         [-2.3104e-01,  1.2913e+00,  4.4618e-01, -9.8944e-01],
         [ 6.0209e-01, -1.6645e+00, -1.2018e+00,  5.0758e-01],
         [-1.1671e+00, -1.2684e-01,  6.5639e-01,  1.6849e-01]],

        [[ 6.0124e-01, -1.0077e-01,  6.2424e-01, -1.3016e+00],
         [-4.0076e-01,  4.8647e-01,  2.9187e-01, -3.8987e-01],
         [ 6.9904e-01,  4.0829e-01,  5.3041e-01, -1.1796e+00],
         [ 7.5499e-01, -6.9229e-01, -3.1246e-01,  3.1820e-02]]])

In [23]:
b

tensor([[[-1.5803, -0.2116, -0.5569,  2.8833],
         [-0.4892,  0.9725, -0.5038,  0.3260],
         [ 0.9377,  0.7405,  1.3478,  1.1064],
         [-0.6396, -2.0126, -0.0208,  1.1039]],

        [[-0.8029,  0.4169,  1.1782, -1.0553],
         [ 0.5588,  0.1266, -0.8120, -0.4711],
         [-0.3019, -1.8486, -0.5260, -0.2419],
         [ 0.0359,  0.9636,  0.3528,  0.1468]]])

In [27]:
tt2 = torch.randn((3,3))
tt2

tensor([[-0.7059, -0.1921, -0.4475],
        [ 1.3753,  0.4166,  0.2604],
        [ 0.3639,  2.6986,  0.5201]])

In [28]:
tt2.t()

tensor([[-0.7059,  1.3753,  0.3639],
        [-0.1921,  0.4166,  2.6986],
        [-0.4475,  0.2604,  0.5201]])

In [37]:
tt3 = torch.arange(2*3*2*3).view(2,3,6)
tt3

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17]],

        [[18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]])

In [38]:
tt3.view(2,3,2,3)

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]],

         [[12, 13, 14],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [21, 22, 23]],

         [[24, 25, 26],
          [27, 28, 29]],

         [[30, 31, 32],
          [33, 34, 35]]]])

In [39]:
tt3.view(2,3,2,3).transpose(1, 2)

tensor([[[[ 0,  1,  2],
          [ 6,  7,  8],
          [12, 13, 14]],

         [[ 3,  4,  5],
          [ 9, 10, 11],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [24, 25, 26],
          [30, 31, 32]],

         [[21, 22, 23],
          [27, 28, 29],
          [33, 34, 35]]]])

In [41]:
tt3.size(-1)

6

In [42]:
tt3.shape

torch.Size([2, 3, 6])

In [43]:
tt3.shape[::-1]

torch.Size([6, 3, 2])

In [44]:
torch.randint(0, 100, (6,))

tensor([15, 85, 81, 56, 47, 37])